### ISSUE TITLE
why is a selfhosted service using a forced oauth model with external providers!? 

### ISSUE THREAD

**Issue by mtojay** [Eugeny/tabby-web#111] opened 2023-12-14 12:54 UTC
i really like tabby. its a great terminal emulator.

but isnt the oauth model kinda going against the selfhosted idea? 

as an option? ok yeah great. more options are better.

but to force an external provider oauth method seems wrong. it compliactes it and also forces you to use services some poeple dont wanna use to begin with.

maybe i am alone with this, but i dont even want to put this on the internet. i want to host this locally on my network and if i need access to it from the outside i will use a wireguard tunnel as i do 99% of my selfhosted services. 

i think ill pass for now. i do think the developer should think about an approach without 3rd party oath providers.

**Comment by Eugeny** [comment] 2023-12-14 13:35
Luckily it's an open-source project, meaning you can work on it :v:

i think ill pass for now. i do think the reporter should think about an approach where they search the open issues first

Duplicate of #33

**Closed by Eugeny** 2023-12-14 13:35 UTC

**Comment by mtojay** [comment] 2023-12-14 13:56
fair enough. for whats its worth i didnt plan to come across as snarky as i probably did. 

thanks for tabby btw. i use it a lot.
